NoGuidance: Print coverage info if -v provided to driver

diff --git a/bin/jqf-random b/bin/jqf-random
--- a/bin/jqf-random
+++ b/bin/jqf-random
@@ -7,12 +7,32 @@ popd > /dev/null
 
 ROOT_DIR=`dirname $BIN_DIR`
 
+print_usage() {
+  echo "Usage: $0 [-c CLASSPATH] [-v] TEST_CLASS TEST_METHOD [MAX_TRIALS]"
+}
+
+while getopts ":c:v" opt; do
+  case $opt in
+    /?)
+      echo "Invalid option: -$OPTARG" >&2
+      print_usage >&1
+      exit 1
+      ;;
+    c)
+      export CLASSPATH="$OPTARG"
+      ;;
+    v)
+      export JVM_OPTS="$JVM_OPTS -Djqf.logCoverage=true"
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
 # Check arguments
-if [ $# -lt 3 ]; then
-  echo "Usage: $0 TEST_CLASS TEST_METHOD MAX_TRIALS" >&2
+if [ $# -lt 2 ]; then
+  print_usage >&1
   exit 1
 fi
 
 # Run the random input driver
-export JQF_DISABLE_INSTRUMENTATION=1
 $ROOT_DIR/scripts/jqf-driver.sh edu.berkeley.cs.jqf.fuzz.drivers.RandomDriver $@
