jqf-afl: Add verbose logging option

diff --git a/bin/jqf-afl b/bin/jqf-afl
--- a/bin/jqf-afl
+++ b/bin/jqf-afl
@@ -7,26 +7,43 @@ popd > /dev/null
 
 ROOT_DIR=`dirname $SCRIPT_DIR`
 
-# Check arguments
-if [ $# -lt 3 ]; then
-  echo "Usage: $0 TEST_CLASS TEST_METHOD INPUT_FILE" >&2
-  exit 1
-fi
-
 # Ensure that proxy is built
 if [ ! -f "$ROOT_DIR/bin/afl-proxy" ]; then
   echo "The AFL proxy is not built! Make sure to run scripts/setup.sh or run 'make' in afl/" >&2
   exit 2
 fi
 
+# Set defaults and parse options to override
 driver="edu.berkeley.cs.jqf.fuzz.drivers.AFLDriver"
+java_log="/dev/null"
+afl_log="/dev/null"
 
-if [ $1 = '-r' ]; then
-  driver="edu.berkeley.cs.jqf.fuzz.drivers.AFLRedundancyDriver"
-  shift 1
+while getopts ":avr" opt; do
+  case $opt in
+    /?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    v)
+      java_log="jqf.log"
+      ;;
+    a)
+      afl_log="proxy.log"
+      ;;
+    r)
+      driver="edu.berkeley.cs.jqf.fuzz.drivers.AFLRedundancyDriver"
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
+# Check positional arguments
+if [ $# -lt 3 ]; then
+  echo "Usage: $0 [-v] [-r] TEST_CLASS TEST_METHOD INPUT_FILE" >&2
+  exit 1
 fi
 
-
+# Ready to go
 class=$1
 method=$2
 input=$3
@@ -42,9 +59,9 @@ mkfifo "$j2a"
 # Run the AFL driver in the background
 "$ROOT_DIR/scripts/jqf-driver.sh" \
   $driver $class $method $input $a2j $j2a \
-  1> /dev/null 2> /dev/null &
+  1> $java_log 2>&1 &
 
 # Run the proxy
-"$ROOT_DIR/bin/afl-proxy" $a2j $j2a
+"$ROOT_DIR/bin/afl-proxy" $a2j $j2a $afl_log
 
 
